/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── shadcn CSS-variable tokens (required by generated components) ──
        border:      'hsl(var(--border))',
        input:       'hsl(var(--input))',
        ring:        'hsl(var(--ring))',
        background:  'hsl(var(--background))',
        foreground:  'hsl(var(--foreground))',
        primary:     { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary:   { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        muted:       { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent:      { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        popover:     { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        card:        { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        sidebar: {
          DEFAULT:              'hsl(var(--sidebar-background))',
          foreground:           'hsl(var(--sidebar-foreground))',
          primary:              'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent:               'hsl(var(--sidebar-accent))',
          'accent-foreground':  'hsl(var(--sidebar-accent-foreground))',
          border:               'hsl(var(--sidebar-border))',
          ring:                 'hsl(var(--sidebar-ring))',
        },
        // ── Vercel design tokens (prose / custom components) ──
        ink:      '#171717',
        canvas:   { DEFAULT: '#ffffff', soft: '#fafafa', 2: '#f5f5f5' },
        content:  { DEFAULT: '#4d4d4d', muted: '#888888' },
        hairline: { DEFAULT: '#ebebeb', strong: '#a1a1a1' },
        link:     { DEFAULT: '#0070f3', deep: '#0761d1', soft: '#d3e5ff' },
        viol:     { DEFAULT: '#7928ca', soft: '#d8ccf1', deep: '#4c2889' },
        vcyan:    { DEFAULT: '#50e3c2', soft: '#aaffec', deep: '#29bc9b' },
        pink:     '#ff0080',
        verr:     { DEFAULT: '#ee0000', soft: '#f7d4d6', deep: '#c50000' },
        vwarn:    { DEFAULT: '#f5a623', soft: '#ffefcf', deep: '#ab570a' },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '48px', letterSpacing: '-0.05em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.04em', fontWeight: '600' }],
        'display-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.04em', fontWeight: '600' }],
        'display-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'body-lg':    ['18px', { lineHeight: '28px', letterSpacing: '0' }],
        'body-md':    ['16px', { lineHeight: '24px', letterSpacing: '0' }],
        'body-sm':    ['14px', { lineHeight: '20px', letterSpacing: '-0.02em' }],
        'caption':    ['12px', { lineHeight: '16px', letterSpacing: '0' }],
        'code':       ['13px', { lineHeight: '20px', letterSpacing: '0' }],
      },
      borderRadius: {
        // shadcn radius tokens (driven by --radius CSS var = 8px)
        lg:  'var(--radius)',
        md:  'calc(var(--radius) - 2px)',
        sm:  'calc(var(--radius) - 4px)',
        // Extra Vercel design tokens
        xs:       '4px',
        xl:       '16px',
        'pill-sm':'64px',
        pill:     '100px',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
      },
      boxShadow: {
        // Vercel stacked elevation — never a single heavy drop
        'card-1': 'inset 0 0 0 1px rgba(0,0,0,0.08)',
        'card-2': 'inset 0 0 0 1px rgba(0,0,0,0.08), 0px 1px 1px rgba(0,0,0,0.02), 0px 2px 2px rgba(0,0,0,0.04)',
        'card-3': 'inset 0 0 0 1px rgba(0,0,0,0.08), 0px 2px 2px rgba(0,0,0,0.04), 0px 8px 8px -8px rgba(0,0,0,0.04)',
        'card-4': 'inset 0 0 0 1px rgba(0,0,0,0.08), 0px 2px 2px rgba(0,0,0,0.04), 0px 8px 16px -4px rgba(0,0,0,0.04)',
        'modal':  'inset 0 0 0 1px rgba(0,0,0,0.08), 0px 1px 1px rgba(0,0,0,0.02), 0px 8px 16px -4px rgba(0,0,0,0.04), 0px 24px 32px -8px rgba(0,0,0,0.06)',
        // Dark mode equivalents
        'card-dark-1': 'inset 0 0 0 1px rgba(255,255,255,0.06)',
        'card-dark-2': 'inset 0 0 0 1px rgba(255,255,255,0.06), 0px 1px 1px rgba(0,0,0,0.3)',
        'card-dark-3': 'inset 0 0 0 1px rgba(255,255,255,0.06), 0px 2px 4px rgba(0,0,0,0.3), 0px 8px 16px rgba(0,0,0,0.2)',
      },
      typography: () => ({
        DEFAULT: {
          css: {
            '--tw-prose-body':        '#4d4d4d',
            '--tw-prose-headings':    '#171717',
            '--tw-prose-lead':        '#4d4d4d',
            '--tw-prose-links':       '#0070f3',
            '--tw-prose-bold':        '#171717',
            '--tw-prose-counters':    '#888888',
            '--tw-prose-bullets':     '#a1a1a1',
            '--tw-prose-hr':          '#ebebeb',
            '--tw-prose-quotes':      '#4d4d4d',
            '--tw-prose-quote-borders': '#ebebeb',
            '--tw-prose-captions':    '#888888',
            '--tw-prose-code':        '#171717',
            '--tw-prose-pre-code':    '#e5e5e5',
            '--tw-prose-pre-bg':      '#171717',
            '--tw-prose-th-borders':  '#ebebeb',
            '--tw-prose-td-borders':  '#ebebeb',
            maxWidth: 'none',
            fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
            fontFeatureSettings: '"ss01", "ss02"',
            a: {
              color: '#0070f3',
              textDecoration: 'none',
              fontWeight: 'inherit',
              '&:hover': { textDecoration: 'underline' },
            },
            'h1,h2,h3,h4,h5,h6': {
              fontWeight: '600',
              color: '#171717',
              scrollMarginTop: '5rem',
              fontFeatureSettings: '"ss01", "ss02"',
            },
            h1: { fontSize: '2rem',  lineHeight: '1',    letterSpacing: '-0.05em' },
            h2: { fontSize: '1.5rem', lineHeight: '1.33', letterSpacing: '-0.04em', marginTop: '2.5rem' },
            h3: { fontSize: '1.25rem', lineHeight: '1.4', letterSpacing: '-0.03em', marginTop: '2rem' },
            code: {
              fontFamily: '"JetBrains Mono", ui-monospace, monospace',
              fontSize: '0.8125em',
              fontWeight: '400',
              backgroundColor: '#f5f5f5',
              borderRadius: '6px',
              paddingLeft:  '0.375em',
              paddingRight: '0.375em',
              paddingTop:    '0.15em',
              paddingBottom: '0.15em',
              '&::before': { content: 'none' },
              '&::after':  { content: 'none' },
            },
            pre: {
              backgroundColor: '#171717',
              borderRadius: '8px',
              padding: '1.25rem',
              margin: '1.5rem 0',
            },
            'pre code': {
              backgroundColor: 'transparent',
              padding: '0',
              fontSize: '0.8125rem',
              fontFamily: '"JetBrains Mono", ui-monospace, monospace',
            },
            table: { fontSize: '0.875em' },
            'thead th': {
              fontFamily: '"JetBrains Mono", ui-monospace, monospace',
              fontSize: '0.75rem',
              fontWeight: '400',
              letterSpacing: '0.05em',
              textTransform: 'uppercase',
              color: '#888888',
              borderBottomColor: '#ebebeb',
            },
            'tbody td': { borderBottomColor: '#ebebeb', verticalAlign: 'top' },
            'blockquote p': { fontStyle: 'normal', color: '#4d4d4d' },
            blockquote: { borderLeftColor: '#ebebeb' },
            hr: { borderColor: '#ebebeb' },
          },
        },
        dark: {
          css: {
            '--tw-prose-body':        '#a1a1a1',
            '--tw-prose-headings':    '#ffffff',
            '--tw-prose-lead':        '#a1a1a1',
            '--tw-prose-links':       '#0070f3',
            '--tw-prose-bold':        '#ffffff',
            '--tw-prose-counters':    '#666666',
            '--tw-prose-bullets':     '#666666',
            '--tw-prose-hr':          '#2a2a2a',
            '--tw-prose-quotes':      '#888888',
            '--tw-prose-quote-borders': '#2a2a2a',
            '--tw-prose-code':        '#e5e5e5',
            '--tw-prose-pre-bg':      '#0a0a0a',
            '--tw-prose-th-borders':  '#2a2a2a',
            '--tw-prose-td-borders':  '#2a2a2a',
            'h1,h2,h3,h4,h5,h6': { color: '#ffffff' },
            'thead th': { color: '#666666', borderBottomColor: '#2a2a2a' },
            'tbody td': { borderBottomColor: '#2a2a2a' },
            blockquote: { borderLeftColor: '#2a2a2a' },
            hr: { borderColor: '#2a2a2a' },
            code: { backgroundColor: '#1f1f1f', color: '#e5e5e5' },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
